version: '3'
services:
  homebridge:
    image: oznu/homebridge:2023-01-08
    container_name: homebridge
    restart: unless-stopped
    network_mode: host
    ports:
      - "8581:8581/tcp"
    environment:
      - TZ=${TIMEZONE}
      - HOMEBRIDGE_CONFIG_UI_PORT=8581
    volumes:
      - ${VOLUMES_PATH}/home-automation/homebridge:/homebridge

volumes:
  homebridge: