version: '3'
services:
  homebridge:
    image: oznu/homebridge:ubuntu
    container_name: homebridge
    restart: unless-stopped
    network_mode: host
    ports:
      - "8581:8581/tcp"
    environment:
      - TZ=${TIMEZONE}
      - HOMEBRIDGE_CONFIG_UI_PORT=8581
    volumes:
      - ${VOLUMES_PATH}/utility-services/homebridge:/homebridge

  wireguard:
    image: lscr.io/linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - TZ=${TIMEZONE}
      - SERVERURL=${DOMAIN_URL}
      - SERVERPORT=51820
      - PEERS=2
      - PEERDNS=auto
      - INTERNAL_SUBNET=10.13.13.0
      - ALLOWEDIPS=0.0.0.0/0
    volumes:
      - ${VOLUMES_PATH}/utility-services/wireguard/config:/config
      - ${VOLUMES_PATH}/utility-services/wireguard/modules:/lib/modules
    ports:
      - "51820:51820/udp"
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped

volumes:
  homebridge: