version: '3'
services:
  homebridge:
    image: oznu/homebridge:ubuntu
    container_name: homebridge
    restart: always
    network_mode: host
    ports:
      - 8581:8581
    environment:
      - TZ=${TIMEZONE}
      - HOMEBRIDGE_CONFIG_UI_PORT=8581
    volumes:
      - ${VOLUMES_PATH}/utility-services/homebridge:/homebridge
volumes:
  homebridge: